const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "0.0.1",
    title: "GoTunes API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/api",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definitions: {},
};

const outputFile = "./swagger-output.json";
const endpointsFiles = [
  "./src/routes/auth.js",
  "./src/routes/artists.js",
  "./src/routes/albums.js",
  "./src/routes/playlists.js",
  // "./src/routes/tracks.js",
  "./src/routes/search.js",
];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // eslint-disable-next-line global-require
  require("./index"); // Your project's root file
});
